### ISSUE TITLE
Story List not colour-coded to reflect edit status

### ISSUE THREAD

**Issue by janrinok** [SoylentNews/SoylentCode#6]
See also https://github.com/SoylentNews/SoylentCode/issues/1 Closed.

The Story List (NOT the submission status list which was corrected in Issue 1 - link above) is usually colour-coded to reflect the editing status of each story i.e. Edited once - Red or Yellow, Edited Twice - Green, Not Displayed (i.e. not released) - Grey).  This does not appear on the devtest display.

**Comment by NCommander** [comment]
Flipped the variable, as I said, this wasn't a coding issue.

**Comment by janrinok** [comment]
Sorry, last time I looked I didn't see the comment - just the fact that it was closed
